spring.application.name=avaliacao-globo

server.port=8080

# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/avaliacao_globo
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# FLYWAY
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# RABBITMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# JACKSON
spring.jackson.serialization.write-dates-as-timestamps=false